name: Generate Node.js packages
run-name: Generate Node.js ${{ inputs.VERSION || '18.12.0' }}
on:
  workflow_dispatch:
   
jobs:
  node:
    name: Node
    uses: aparnajyothi-y/versions-package-tools/.github/workflows/build-tool-packages.yml@node-arm64-support
    with:
      tool-name: "node"
      tool-version: ${{ inputs.VERSION || '18.12.0' }}
    secrets: inherit
